// AUTO-GENERATED by scripts/postprocess_sprites.py -- do not edit by hand.
// Ids of monsters that have real pixel-art sprites in public/sprites/<id>/.
export const SPRITE_IDS: string[] = ["brasita_bb", "brotecito", "carpinchon", "charquito", "chispita", "gotita", "matecito", "pelusin", "termito", "terroncito", "ventacito", "yaguarete_rey"];
