"""Turn every raw sprite in sprites-raw/ into game-ready frames + a manifest.

For each sprites-raw/<id>.png: flood-fill the light-grey background to transparent
from the corners, trim to content, center bottom-aligned on a square canvas, and
emit a 2-frame idle (idle_0 normal, idle_1 a subtle squash so it 'breathes').
Then (re)write src/game/data/spriteManifest.ts listing the ids that have art, so
MonsterSprite shows the real sprite for those and the procedural one for the rest.

Run after each generation batch:
  uv run --no-project --with pillow python scripts/postprocess_sprites.py
"""
from pathlib import Path
from PIL import Image, ImageDraw

SIZE = 256
CONTENT = 212
BASELINE = SIZE - 16
SRC_DIR = Path("sprites-raw")
OUT_DIR = Path("public/sprites")
MANIFEST = Path("src/game/data/spriteManifest.ts")


def corners_dark(im: Image.Image) -> bool:
    g = im.convert("L")
    w, h = g.size
    s = max(8, w // 16)
    boxes = [(0, 0, s, s), (w - s, 0, w, s)]
    means = [sum(g.crop(b).getdata()) / (s * s) for b in boxes]
    return min(means) < 120


def remove_bg(im: Image.Image) -> Image.Image:
    im = im.convert("RGBA")
    w, h = im.size
    for seed in [(1, 1), (w - 2, 1), (1, h - 2), (w - 2, h - 2)]:
        ImageDraw.floodfill(im, seed, (0, 0, 0, 0), thresh=60)
    return im


def frame(content: Image.Image, squash: float) -> Image.Image:
    cw, ch = content.size
    scale = CONTENT / max(cw, ch)
    nw, nh = max(1, int(cw * scale)), max(1, int(ch * scale * squash))
    sprite = content.resize((nw, nh), Image.LANCZOS)
    canvas = Image.new("RGBA", (SIZE, SIZE), (0, 0, 0, 0))
    canvas.paste(sprite, ((SIZE - nw) // 2, BASELINE - nh), sprite)
    return canvas


def main():
    ids = []
    for src in sorted(SRC_DIR.glob("*.png")):
        mid = src.stem
        im = Image.open(src)
        if corners_dark(im):
            print(f"{mid}: looks like a safety placeholder, skipped", flush=True)
            continue
        content = remove_bg(im)
        bbox = content.getbbox()
        if bbox:
            content = content.crop(bbox)
        out = OUT_DIR / mid
        out.mkdir(parents=True, exist_ok=True)
        frame(content, 1.0).save(out / "idle_0.png")
        frame(content, 0.94).save(out / "idle_1.png")
        ids.append(mid)
        print(f"{mid}: ok", flush=True)

    arr = ", ".join(f'"{i}"' for i in sorted(ids))
    MANIFEST.write_text(
        "// AUTO-GENERATED by scripts/postprocess_sprites.py -- do not edit by hand.\n"
        "// Ids of monsters that have real pixel-art sprites in public/sprites/<id>/.\n"
        f"export const SPRITE_IDS: string[] = [{arr}];\n",
        encoding="utf-8",
    )
    print(f"\nmanifest: {len(ids)} sprites -> {MANIFEST}", flush=True)


if __name__ == "__main__":
    main()
